name: Cafe Iran Front CI-CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Connect & Execute Commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          script: |
            cd ${{secrets.FRONT_PATH}}
            git pull
            npm i --force
            npm run build
            pm2 restart ${{secrets.PM2_ID}}
            sudo systemctl restart nginx.service